# Generated by Django 6.0.1 on 2026-02-13 10:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phonenumber', models.CharField(max_length=15, unique=True)),
                ('current_password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('farmer', 'Farmer'), ('worker', 'Worker')], max_length=10)),
                ('work_time', models.CharField(blank=True, choices=[('morning', 'Morning'), ('evening', 'Evening')], max_length=10, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'User Register',
                'verbose_name_plural': 'User Registers',
            },
        ),
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_size', models.DecimalField(blank=True, decimal_places=2, help_text='Land size in acres', max_digits=10, null=True)),
                ('total_works_posted', models.PositiveIntegerField(default=0)),
                ('total_workers_hired', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=0, help_text='Average rating out of 5', max_digits=3)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to='members.userregister')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('required_workers', models.PositiveIntegerField(default=1)),
                ('wage_amount', models.DecimalField(decimal_places=2, help_text='Wage per worker', max_digits=10)),
                ('wage_type', models.CharField(choices=[('per_day', 'Per Day'), ('total', 'Total')], default='per_day', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('contact_phone', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_works', to='members.userregister')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_works', to='members.userregister')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('worker_share', models.DecimalField(decimal_places=2, help_text='95% of total amount', max_digits=12)),
                ('admin_commission', models.DecimalField(decimal_places=2, help_text='5% of total amount', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('paid', 'Paid')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to='members.userregister')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to='members.userregister')),
                ('work', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='members.work')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('earned', 'Earned'), ('paid', 'Paid')], default='earned', max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='members.payment')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='members.work')),
            ],
            options={
                'verbose_name_plural': 'Commissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField(blank=True, help_text='Comma-separated list of skills', null=True)),
                ('experience_years', models.PositiveIntegerField(default=0, help_text='Years of experience')),
                ('total_works_completed', models.PositiveIntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rating', models.DecimalField(decimal_places=2, default=0, help_text='Average rating out of 5', max_digits=3)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to='members.userregister')),
            ],
        ),
        migrations.CreateModel(
            name='WorkApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='applied', max_length=15)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='members.work')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_applications', to='members.userregister')),
            ],
            options={
                'unique_together': {('work', 'worker')},
            },
        ),
    ]
